### ISSUE TITLE
THE APP FORCE CLOSE 

### ISSUE THREAD

**Issue by ced1988** [Thomasyse/BDMatch#2]
when i drop the file the app force close 

thanks to fix 
https://mega.nz/#!BXo0Sa5Q!Le0OGF9f_zx6-Sn3u-PNHVuTyaI16SM8kyx4A8ROK3Q

**Comment by Thomasyse** [comment]
This issue is caused by the restriction of audio channels. I will lift this restriction in next release soon. 

However, it is not recommended to fill in the input files with over 2 channels since it consumes large memory and the results are not verified.

The good news is the result of the input here seems correct.
